apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.acme.io
  annotations:
    description: "Database cluster management resource for Acme Corp applications"
    category: "database"
spec:
  group: acme.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object
            required: ["engine", "version"]
            properties:
              engine:
                type: string
                enum: ["postgresql", "mysql", "redis", "mongodb"]
                description: "Database engine type"
              version:
                type: string
                description: "Database engine version"
                pattern: "^[0-9]+\\.[0-9]+$"
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                default: 3
                description: "Number of database replicas"
              storage:
                type: object
                required: ["size"]
                properties:
                  size:
                    type: string
                    pattern: "^[0-9]+[KMGT]i$"
                    description: "Storage size per replica"
                  storageClass:
                    type: string
                    default: "fast-ssd"
                    description: "Kubernetes storage class"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: "^[0-9]+m?$"
                      memory:
                        type: string
                        pattern: "^[0-9]+[KMGT]i$"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: "^[0-9]+m?$"
                      memory:
                        type: string
                        pattern: "^[0-9]+[KMGT]i$"
              backup:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  schedule:
                    type: string
                    pattern: "^[0-9*/-,]+\\s+[0-9*/-,]+\\s+[0-9*/-,]+\\s+[0-9*/-,]+\\s+[0-9*/-,]+$"
                    default: "0 2 * * *"
                  retention:
                    type: string
                    pattern: "^[0-9]+[dwhm]$"
                    default: "30d"
              security:
                type: object
                properties:
                  encryption:
                    type: object
                    properties:
                      atRest:
                        type: boolean
                        default: true
                      inTransit:
                        type: boolean
                        default: true
                  authentication:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      method:
                        type: string
                        enum: ["password", "certificate", "iam"]
                        default: "password"
              monitoring:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  metricsPort:
                    type: integer
                    minimum: 1024
                    maximum: 65535
                    default: 9187
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Running", "Updating", "Failed", "Maintenance"]
              replicas:
                type: integer
              readyReplicas:
                type: integer
              primaryEndpoint:
                type: string
              replicaEndpoints:
                type: array
                items:
                  type: string
              lastBackup:
                type: string
                format: date-time
              health:
                type: string
                enum: ["Healthy", "Warning", "Critical"]
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db
    categories:
    - databases
    - acme