apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.acme.io
  annotations:
    description: "Web application deployment and management resource for Acme Corp"
    category: "application"
spec:
  group: acme.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object
            required: ["image", "domain"]
            properties:
              image:
                type: string
                description: "Container image to deploy"
                pattern: "^[a-zA-Z0-9._/-]+:[a-zA-Z0-9._-]+$"
              domain:
                type: string
                description: "Primary domain for the web application"
                pattern: "^[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
              replicas:
                type: integer
                minimum: 1
                maximum: 100
                default: 3
                description: "Number of application replicas"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: "^[0-9]+m?$"
                      memory:
                        type: string
                        pattern: "^[0-9]+[KMGT]i?$"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: "^[0-9]+m?$"
                      memory:
                        type: string
                        pattern: "^[0-9]+[KMGT]i?$"
              scaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  minReplicas:
                    type: integer
                    minimum: 1
                    default: 3
                  maxReplicas:
                    type: integer
                    minimum: 1
                    default: 10
                  targetCPU:
                    type: integer
                    minimum: 10
                    maximum: 90
                    default: 70
              monitoring:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  port:
                    type: integer
                    minimum: 1024
                    maximum: 65535
                    default: 8080
                  path:
                    type: string
                    default: "/metrics"
              security:
                type: object
                properties:
                  runAsNonRoot:
                    type: boolean
                    default: true
                  readOnlyRootFilesystem:
                    type: boolean
                    default: false
                  allowedRegistries:
                    type: array
                    items:
                      type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Updating", "Failed"]
              replicas:
                type: integer
              readyReplicas:
                type: integer
              url:
                type: string
              lastUpdated:
                type: string
                format: date-time
  scope: Namespaced
  names:
    plural: webapps
    singular: webapp
    kind: WebApp
    shortNames:
    - wa
    categories:
    - applications
    - acme