name: Claude Code Review

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: string
      review_scope:
        description: 'Review scope'
        required: false
        default: 'full'
        type: choice
        options:
        - full
        - security
        - performance
        - style

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Validate inputs
        run: |
          echo "🤖 Starting Claude Code Review"
          echo "PR Number: ${{ github.event.inputs.pr_number }}"
          echo "Review Scope: ${{ github.event.inputs.review_scope }}"
          echo "Triggered by: ${{ github.actor }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Please review PR #${{ github.event.inputs.pr_number }} with a focus on: ${{ github.event.inputs.review_scope }}

            Review scope guidelines:
            - full: Complete code review covering all aspects
            - security: Focus on security vulnerabilities and best practices
            - performance: Focus on performance issues and optimizations
            - style: Focus on code style, formatting, and conventions

            For all reviews, please provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Test coverage (if applicable)

            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            Steps:
            1. Use `gh pr view ${{ github.event.inputs.pr_number }}` to get PR details
            2. Use `gh pr diff ${{ github.event.inputs.pr_number }}` to see the changes
            3. Review the code changes according to the specified scope
            4. Use `gh pr comment ${{ github.event.inputs.pr_number }} --body "your review"` to post your review

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

